openapi: "3.0.0"
components:
  schemas:
    StringValue:
      type: object
      required:
        - value
      properties:
        value:
          type: string
    BooleanValue:
      type: object
      required:
        - value
      properties:
        value:
          type: boolean
    AmountValue:
      type: object
      required:
        - value
      properties:
        value:
          type: number
    ByteArray:
      required:
        - data
      type: object
      properties:
        data:
          type: string
          format: binary
    ByteArrayValue:
      required:
        - value
      type: object
      properties:
        value:
          $ref: "#/components/schemas/ByteArray"
    FieldValue:
      oneOf:
        - $ref: "#/components/schemas/StringValue"
        - $ref: "#/components/schemas/BooleanValue"
        - $ref: "#/components/schemas/AmountValue"
        - $ref: "#/components/schemas/ByteArrayValue"
    FieldValueMap:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/FieldValue"
